### PR TITLE
add access for super admin

### PR DESCRIPTION
**Pull request by itkg-rboessel**

### CODE REVIEW

**Comment by itkg-rboessel** [comment]
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1022
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/40

**Comment by alavieille** [comment]
can you update tests ?

**Comment by itkg-rboessel** [comment]
@itkg-alavieille done

**Comment by itkg-rboessel** [comment]
@itkg-alavieille  done

**Comment by alavieille** [comment]
:+1:

**Pull request merged**
